# Лабораторная работа №3
## Выполнил студент группы Суроп Максим Андреевич БВТ2005

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
4. [Вывод](#Вывод)

> Дополнительные модули, использованные при выполнение лабораторной

In [11]:
# Необходим при замере скорости выполнения кода
from datetime import datetime as t
# Нужен для создания словаря в алг. Бойера-Мура
from collections import defaultdict

### Задание №1
Реализовать методы поиска подстроки в строке. Добавить возможность ввода строки и подстроки с клавиатуры. Предусмотреть возможность существования пробела. Реализовать возможность выбора опции чувствительности или нечувствительности к регистру. Оценить время работы каждого алгоритма поиска и сравнить его со временем работы стандартной функции поиска, используемой в выбранном языке программирования.

#### Алгоритм Кнута-Морриса-Пратта

In [12]:
def prefix_function(text):
    n = len(text)
    pi = [0] * n  
    for i in range(1, n):
        j = pi[i-1]
        while j > 0 and text[j] != text[i]:
            j = pi[j-1]
        if text[i] == text[j]:
            j += 1
        pi[i] = j
    return pi

def kmp_search(string, substring, start_index = 0):
    j = 0
    pi = prefix_function(substring)
    for i in range(start_index, len(string)):
        while j > 0 and string[i] != substring[j]:
            j = pi[j-1]
        if string[i] == substring[j]:
            j += 1
        if j >= len(substring):
            return i - j + 1
    return None

input_string = input("Введите строку: ")
input_substring = input("Введите подстроку: ")
sens = input("Чувствительность к регистру: ")

if (sens == "False"):
    input_string = input_string.lower()
    input_substring = input_substring.lower()

time_start = t.now()
print("Индекс начала: ", kmp_search(input_string, input_substring, 0))
time_end = t.now()
print("Продолжительность: {}".format(time_end - time_start))

time_start = t.now()
print("Индекс начала: ", input_string.find(input_substring))
time_end = t.now()
print("Продолжительность: {}".format(time_end - time_start))

Введите строку: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Введите подстроку: magna
Чувствительность к регистру: False
Индекс начала:  110
Продолжительность: 0:00:00
Индекс начала:  110
Продолжительность: 0:00:00


#### Упрощенный алгоритм Бойера-Мура

In [13]:
def bm_search(line, subline, reg):
    if len(line) < len(subline):
        return -1
    if reg == 0:
        line = line.lower()
        subline = subline.lower()
    d = defaultdict()
    s = set()
    N = len(line)
    M = len(subline)
    for i in range(M - 2, -1, -1):
        if subline[i] not in s:
            d[subline[i]] = M - i - 1
            s.add(subline[i])
    if subline[M - 1] not in s:
        d[subline[M - 1]] = M
    d['*'] = M
    i = M - 1
    while i < N:
        k = 0
        for j in range(M - 1, -1, -1):
            if line[i - k] != subline[j]:
                if j == M - 1:
                    offset = d[line[i]] if d.get(line[i], False) else d['*']
                else:
                    offset = d[subline[j]]
                i += offset
                break
            k += 1
        
        if j == 0:
            return i - k + 1
    return -1

input_string = input("Введите строку: ")
input_substring = input("Введите подстроку: ")
sens = input("Чувствительность к регистру: ")

if (sens == "False"):
    input_string = input_string.lower()
    input_substring = input_substring.lower()

time_start = t.now()
print("Индекс начала: ", bm_search(input_string, input_substring, 0))
time_end = t.now()
print("Продолжительность: {}".format(time_end - time_start))

Введите строку: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Введите подстроку: magna
Чувствительность к регистру: False
Индекс начала:  110
Продолжительность: 0:00:00


### Задание №2
Написать программу, определяющую, является ли данное
расположение «решаемым», то есть можно ли из него за конечное число
шагов перейти к правильному. Если это возможно, то необходимо найти хотя
бы одно решение - последовательность движений, после которой числа будут
расположены в правильном порядке.
#### Входные данные: массив чисел, представляющий собой расстановку в
Порядке «слева направо, сверху вниз». Число 0 обозначает пустое поле.
Например, массив [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0] представляет
собой «решенную» позицию элементов.
#### Выходные данные: если решения нет, то функция должна вернуть
Пустой массив []. Если решение есть, то необходимо представить решение —
для каждого шага записывается номер передвигаемого на данном шаге
элемента. 

In [25]:
import numpy as np
import itertools

array = np.array([2,6,13,7,8,10,15,1,0,3,4,5,9,11,12,14])

array = array.reshape(4,4)

print(str(array) + '\n')

def sort_by_columns(array):
    lst = sorted(itertools.chain.from_iterable(array))
    return [lst[i::len(array)] for i in range(len(array))]
    

array = np.array(sort_by_columns(array))

print(str(array) + '\n')

array = np.transpose(array)

print(str(array) + '\n')

array = np.delete(array, 0)
array = np.append(array, 0)
print(array.reshape(4,4))

[[ 2  6 13  7]
 [ 8 10 15  1]
 [ 0  3  4  5]
 [ 9 11 12 14]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


### Вывод